# Generated by Django 4.2.17 on 2025-01-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreferences',
            old_name='criteria',
            new_name='kryterium',
        ),
        migrations.RenameField(
            model_name='userpreferences',
            old_name='stock_list',
            new_name='lista_krajów',
        ),
        migrations.RenameField(
            model_name='userpreferences',
            old_name='weights',
            new_name='sektory',
        ),
    ]
