# Generated by Django 4.2.17 on 2025-01-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_criteria_userpreferences_kryterium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='wagi',
            field=models.TextField(blank=True, default=''),
        ),
    ]
