# Generated by Django 4.2.17 on 2025-01-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userpreferences_wagi'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='n_co1',
            field=models.IntegerField(default=100),
        ),
    ]
