# Generated by Django 4.2.17 on 2025-01-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_userpreferences_n_co1'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='markowitz_choices',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='risk_method',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='risk_metric_choices',
            field=models.TextField(blank=True, default=''),
        ),
    ]
