# Generated by Django 4.2.17 on 2025-02-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_userpreferences_markowitz_choices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='markowitz_choices',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='n_co1',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='risk_method',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='risk_metric_choices',
        ),
    ]
